import assert from "node:assert/strict";
import fs from "node:fs";
const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),"utf8");
const html=read("index.html"),boot=read("js/boot-check.js"),bootstrap=read("js/bootstrap.js"),app=read("js/app.js"),sw=read("sw.js");
assert.match(html,/script defer src="\.\/js\/bootstrap\.js"/);
assert.doesNotMatch(html,/type="module" src="\.\/js\/app\.js"/);
assert.match(bootstrap,/VERSION="1\.0\.0"/);
assert.match(bootstrap,/EXPECTED_CACHE="chopper-native-mp3-v1-cache-1"/);
assert.match(bootstrap,/chopper-native-mp3-v1-/);
assert.match(bootstrap,/await import\(`\.\/app\.js\?v=/);
assert.match(boot,/8000/);
assert.match(boot,/audio-mp3-app-ready/);
assert.match(app,/window\.__AUDIO_MP3_APP_READY__=true/);
assert.match(sw,/chopper-native-mp3-v1-cache-1/);
assert.match(sw,/\.\/js\/bootstrap\.js/);
assert.match(sw,/e\.request\.mode==="navigate"/);
assert.match(sw,/cache:"no-store"/);
assert.match(bootstrap,/RESET_PARAM="_nmp3reset"/);
assert.match(bootstrap,/location\.replace/);
console.log("PASS NativeMP3Converter V1.0 bootstrap/cache isolation contract");
