from __future__ import annotations
from pathlib import Path
import re, json

ROOT = Path(__file__).resolve().parents[1]
JS = ROOT / 'js'

IMPORT_RE = re.compile(r'^\s*import\s*\{([^}]+)\}\s*from\s*["\']([^"\']+)["\'];?\s*$', re.M)
EXPORT_DECL_RE = re.compile(r'^(\s*)export\s+(async\s+function|function|class|const|let|var)\s+([A-Za-z_$][\w$]*)', re.M)
EXPORT_LIST_RE = re.compile(r'^\s*export\s*\{([^}]+)\};?\s*$', re.M)

class Bundler:
    def __init__(self, base: Path):
        self.base = base
        self.namespaces: dict[Path, str] = {}
        self.emitted: set[Path] = set()
        self.parts: list[str] = []

    def ns(self, path: Path) -> str:
        path = path.resolve()
        if path not in self.namespaces:
            rel = path.relative_to(ROOT).as_posix()
            safe = re.sub(r'[^A-Za-z0-9_$]', '_', rel)
            self.namespaces[path] = f'__mod_{safe}'
        return self.namespaces[path]

    def resolve(self, importer: Path, spec: str) -> Path:
        if not spec.startswith('.'):
            raise RuntimeError(f'Only relative imports supported: {spec} in {importer}')
        p = (importer.parent / spec).resolve()
        if not p.exists():
            raise FileNotFoundError(f'Missing import {spec} from {importer}')
        return p

    def analyze(self, path: Path):
        text = path.read_text(encoding='utf-8')
        imports = []
        for m in IMPORT_RE.finditer(text):
            names = [x.strip() for x in m.group(1).split(',') if x.strip()]
            imports.append((m.group(0), names, self.resolve(path, m.group(2))))
        exports = []
        for m in EXPORT_DECL_RE.finditer(text):
            exports.append(m.group(3))
        for m in EXPORT_LIST_RE.finditer(text):
            for item in m.group(1).split(','):
                item = item.strip()
                if not item:
                    continue
                if ' as ' in item:
                    left, right = re.split(r'\s+as\s+', item, maxsplit=1)
                    exports.append((left.strip(), right.strip()))
                else:
                    exports.append(item)
        return text, imports, exports

    def emit_module(self, path: Path):
        path = path.resolve()
        if path in self.emitted:
            return
        text, imports, exports = self.analyze(path)
        for _, _, dep in imports:
            self.emit_module(dep)

        for full, names, dep in imports:
            destruct = []
            for name in names:
                if ' as ' in name:
                    src, dst = re.split(r'\s+as\s+', name, maxsplit=1)
                    destruct.append(f'{src.strip()}: {dst.strip()}')
                else:
                    destruct.append(name)
            text = text.replace(full, f"const {{{', '.join(destruct)}}} = {self.ns(dep)};")
        text = re.sub(r'^(\s*)export\s+(?=(?:async\s+function|function|class|const|let|var)\b)', r'\1', text, flags=re.M)
        text = EXPORT_LIST_RE.sub('', text)

        ret_items=[]
        for e in exports:
            if isinstance(e, tuple):
                ret_items.append(f'{e[1]}: {e[0]}')
            else:
                ret_items.append(e)
        rel = path.relative_to(ROOT).as_posix()
        self.parts.append(
            f"\n// ---- bundled module: {rel} ----\n"
            f"const {self.ns(path)} = (()=>{{\n'use strict';\n{text}\nreturn {{{', '.join(ret_items)}}};\n}})();\n"
        )
        self.emitted.add(path)

    def build_entry(self, entry: Path, prelude: str = '', transform=None) -> str:
        entry = entry.resolve()
        text, imports, _ = self.analyze(entry)
        for _, _, dep in imports:
            self.emit_module(dep)
        for full, names, dep in imports:
            destruct=[]
            for name in names:
                if ' as ' in name:
                    src, dst = re.split(r'\s+as\s+', name, maxsplit=1)
                    destruct.append(f'{src.strip()}: {dst.strip()}')
                else:
                    destruct.append(name)
            text=text.replace(full, f"const {{{', '.join(destruct)}}} = {self.ns(dep)};")
        if transform:
            text=transform(text)
        return "/* Generated by scripts/build_classic_bundle.py. Runtime has no ES-module import graph. */\n'use strict';\n" + prelude + ''.join(self.parts) + "\n// ---- bundled entry ----\n(()=>{\n'use strict';\n" + text + "\n})();\n"


def build_worker() -> str:
    b=Bundler(JS)
    return b.build_entry(JS/'mp3'/'encoder-worker.js')


def transform_app(text: str) -> str:
    old='const worker=new Worker(new URL("./mp3/encoder-worker.js",import.meta.url),{type:"module"});'
    new='const workerURL=URL.createObjectURL(new Blob([ENCODER_WORKER_SOURCE],{type:"text/javascript"}));const worker=new Worker(workerURL);'
    if old not in text:
        raise RuntimeError('Worker creation pattern not found; refusing to build stale bundle')
    text=text.replace(old,new)
    old_cleanup='const cleanup=()=>{if(activeEncodeTask?.worker===worker)activeEncodeTask=null;try{worker.terminate()}catch{}};'
    new_cleanup='const cleanup=()=>{if(activeEncodeTask?.worker===worker)activeEncodeTask=null;try{worker.terminate()}catch{}try{URL.revokeObjectURL(workerURL)}catch{}};'
    if old_cleanup not in text:
        raise RuntimeError('Worker cleanup pattern not found; refusing to build stale bundle')
    text=text.replace(old_cleanup,new_cleanup)
    return text

worker=build_worker()
app_b=Bundler(JS)
prelude='const ENCODER_WORKER_SOURCE = ' + json.dumps(worker, ensure_ascii=False) + ';\n'
app=app_b.build_entry(JS/'app.js', prelude=prelude, transform=transform_app)
(JS/'app.bundle.js').write_text(app,encoding='utf-8',newline='\n')
print(f'Wrote {JS/"app.bundle.js"} ({len(app.encode("utf-8"))} bytes)')
print(f'Embedded worker: {len(worker.encode("utf-8"))} bytes')
