import assert from "node:assert/strict";
import fs from "node:fs";
const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),"utf8");
const html=read("index.html"),boot=read("js/boot-check.js"),app=read("js/app.js"),sw=read("sw.js");
assert.match(html,/script type="module" src="\.\/js\/app\.js"/);
assert.doesNotMatch(html,/bootstrap\.js/);
assert.doesNotMatch(html,/app\.js\?v=/);
assert.match(boot,/15000/);
assert.match(boot,/fetch\("\.\/js\/app\.js"/);
assert.match(boot,/audio-mp3-app-ready/);
assert.match(app,/window\.__AUDIO_MP3_APP_READY__=true/);
assert.match(app,/audio-mp3-app-ready/);
assert.match(app,/audio-mp3-app-error/);
assert.match(sw,/chopper-native-mp3-v1-cache-2/);
assert.doesNotMatch(sw,/bootstrap\.js/);
assert.match(sw,/e\.request\.mode==="navigate"/);
assert.match(sw,/cache:"no-store"/);
assert.match(sw,/const hit=await cache\.match\(e\.request\)/);
console.log("PASS NativeMP3Converter V1.0.1 direct-module boot/cache contract");
