import assert from "node:assert/strict";
import {sanitizeSegment,normalizeRelativePath,joinPath,isMp3,extOf,csvEscape,hasPathSegment,isPathInside} from "../js/path-utils.js";
import {fileFingerprint,isStrongFingerprint} from "../js/fingerprint.js";
import {putOutput,getOutput,deleteOutput,clearOutputs,outputStoreStatus,cleanupExpiredOutputs} from "../js/output-store.js";
import {makeStoreZip,safeZipPath} from "../js/zip-store.js";
import {estimatePcmWorkingSet,memoryPolicy} from "../js/pcm-safety.js";
import {encodeMp3,NATIVE_MP3_INFO,StreamingMp3Encoder} from "../js/mp3/native-mp3-encoder.js";
import {inspectMp3Bytes,validateMp3Structure} from "../js/mp3/mp3-validator.js";
import {inspectWavFile} from "../js/wav-stream.js";
import {streamWavToMp3} from "../js/wav-mp3-streamer.js";

assert.equal(NATIVE_MP3_INFO.coreVersion,"0.4.1");assert.equal(NATIVE_MP3_INFO.streaming,true);assert.deepEqual(NATIVE_MP3_INFO.sampleRates,[32000,44100,48000]);assert.deepEqual(NATIVE_MP3_INFO.bitrates,[64,96,128,192,256,320]);assert.equal(NATIVE_MP3_INFO.dependencies,0);assert.equal(NATIVE_MP3_INFO.wasm,false);
function sine(freq,seconds=.18,amp=.25,rate=44100){const n=Math.floor(rate*seconds),a=new Float32Array(n);for(let i=0;i<n;i++)a[i]=amp*Math.sin(2*Math.PI*freq*i/rate);return a}
function complex(seconds=.45,rate=44100){const n=Math.floor(rate*seconds),l=new Float32Array(n),r=new Float32Array(n);for(let i=0;i<n;i++){const t=i/rate,hit=i%4096<6?.32:0;l[i]=.16*Math.sin(2*Math.PI*440*t)+.11*Math.sin(2*Math.PI*3600*t)+.07*Math.sin(2*Math.PI*9000*t)+hit;r[i]=.15*Math.sin(2*Math.PI*660*t)+.10*Math.sin(2*Math.PI*5300*t)+.06*Math.sin(2*Math.PI*11000*t)-hit*.4}return[l,r]}
for(const rate of NATIVE_MP3_INFO.sampleRates){const out=encodeMp3([sine(440,.2,.25,rate)],{bitrate:128,sampleRate:rate}),info=inspectMp3Bytes(out);assert.ok(info);assert.equal(info.sampleRate,rate);assert.equal(info.bitrate,128);assert.equal(info.channels,1)}
for(const kbps of NATIVE_MP3_INFO.bitrates){const out=encodeMp3([sine(440)],{bitrate:kbps}),info=inspectMp3Bytes(out);assert.ok(info);assert.equal(info.bitrate,kbps)}
// Streaming core must match valid frame structure when PCM arrives in irregular chunks.
const pcm=sine(550,.37,.3),enc=new StreamingMp3Encoder({channels:1,bitrate:128,sampleRate:44100,inputScale:1}),parts=[];let p=0;for(const n of [777,4096,333,8192,99999]){if(p>=pcm.length)break;parts.push(...enc.push([pcm.subarray(p,Math.min(p+n,pcm.length))]));p+=n}if(p<pcm.length)parts.push(...enc.push([pcm.subarray(p)]));parts.push(...enc.flush());const streamBytes=new Uint8Array(parts.reduce((s,x)=>s+x.length,0));let q=0;for(const x of parts){streamBytes.set(x,q);q+=x.length}assert.ok(inspectMp3Bytes(streamBytes));
// Quality ladder regression.
function usage(bitrate){let used=0,cap=0;encodeMp3(complex(),{bitrate,onStats:s=>{used+=s.usedBits;cap+=s.mainCapacity}});return{used,ratio:used/cap}}const u64=usage(64),u128=usage(128),u320=usage(320);assert.ok(u128.used>u64.used*1.4);assert.ok(u320.used>u128.used*1.8);assert.ok(u320.ratio>.70);
let peakProtected=false;encodeMp3([sine(440,.08,1.2)],{bitrate:128,onStats:s=>{peakProtected ||= s.inputScale<1}});assert.equal(peakProtected,true);

function makeWav({rate=48000,channels=2,seconds=.22,bits=16}={}){const frames=Math.floor(rate*seconds),bps=bits/8,align=channels*bps,dataSize=frames*align,ab=new ArrayBuffer(44+dataSize),v=new DataView(ab);const ascii=(o,t)=>[...t].forEach((c,i)=>v.setUint8(o+i,c.charCodeAt(0)));ascii(0,"RIFF");v.setUint32(4,36+dataSize,true);ascii(8,"WAVE");ascii(12,"fmt ");v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,channels,true);v.setUint32(24,rate,true);v.setUint32(28,rate*align,true);v.setUint16(32,align,true);v.setUint16(34,bits,true);ascii(36,"data");v.setUint32(40,dataSize,true);let o=44;for(let i=0;i<frames;i++){for(let ch=0;ch<channels;ch++){const sample=Math.sin(2*Math.PI*(440+ch*220)*i/rate)*.25;v.setInt16(o,Math.round(sample*32767),true);o+=2}}return new Blob([ab],{type:"audio/wav"})}
const wav=makeWav(),wi=await inspectWavFile(wav);assert.equal(wi.streamable,true);assert.equal(wi.sampleRate,48000);const streamed=await streamWavToMp3(wav,{bitrate:192,collect:true});assert.equal(streamed.sampleRate,48000);assert.ok(streamed.encoderStats.streaming);const validated=await validateMp3Structure(streamed.blob);assert.equal(validated.sampleRate,48000);assert.equal(validated.bitrate,192);assert.equal(validated.channels,2);

const estStereoHour=estimatePcmWorkingSet({duration:3600,channels:2,sourceBytes:80*1024*1024});assert.ok(estStereoHour>2*1024*1024*1024);const policy=memoryPolicy({deviceMemoryGB:4,mobile:true,lowMemory:true});assert.ok(policy.soft<policy.hard);assert.ok(policy.hard<=600*1024*1024);
assert.equal(sanitizeSegment("CON"),"_CON");assert.equal(sanitizeSegment("abc. "),"abc");assert.equal(normalizeRelativePath("../A/../B/test?.m4a"),"A/B/test_.m4a");assert.equal(joinPath("A\\B","C.mp3"),"A/B/C.mp3");assert.equal(isMp3("TEST.MP3"),true);assert.equal(extOf("x.m4a"),"m4a");assert.equal(csvEscape('a,"b"'),'"a,""b"""');assert.equal(csvEscape("=1+1").startsWith("'"),true);assert.equal(csvEscape("  +1").startsWith("'"),true);assert.equal(hasPathSegment("9月/MP3_轉換結果/x.mp3","MP3_轉換結果"),true);assert.equal(isPathInside("完成MP3/北區/a.mp3","完成MP3"),true);assert.equal(isPathInside("完成MP32/a.mp3","完成MP3"),false);assert.equal(safeZipPath("A/B.mp3"),"A/B.mp3");assert.throws(()=>safeZipPath("../evil.mp3"));assert.throws(()=>safeZipPath("/abs.mp3"));
if(typeof File!=="undefined"){const f1=new File([new Uint8Array(200000).fill(7)],"a.m4a",{lastModified:123});const f2=new File([new Uint8Array(200000).fill(7)],"a.m4a",{lastModified:123});const changed=new Uint8Array(200000).fill(7);changed[100000]=8;const f3=new File([changed],"a.m4a",{lastModified:123});assert.equal(await fileFingerprint(f1),await fileFingerprint(f2));assert.notEqual(await fileFingerprint(f1),await fileFingerprint(f3));assert.equal(isStrongFingerprint(await fileFingerprint(f1)),true)}
await clearOutputs();const storageMode=await putOutput("fallback-test",streamed.blob,{outputDuration:.22,encoder:"native-0.4.1"});assert.equal(storageMode,"memory");assert.equal((await getOutput("fallback-test")).size,streamed.blob.size);assert.equal(outputStoreStatus().fallbackUsed,true);await cleanupExpiredOutputs();await deleteOutput("fallback-test");assert.equal(await getOutput("fallback-test"),null);
const zip=await makeStoreZip([{name:"MP3_轉換結果/北區/測試.mp3",blob:streamed.blob,date:new Date("2026-01-01T00:00:00Z")}]);const head=new Uint8Array(await zip.slice(0,4).arrayBuffer());assert.deepEqual([...head],[0x50,0x4b,0x03,0x04]);await assert.rejects(()=>makeStoreZip([{name:"../evil.mp3",blob:new Blob([1])}]));
console.log("PASS NativeMP3Converter V1.0 Native Core v0.4.1 streaming / WAV / MP3 structure / CSV injection / ZIP path / cache tests");
